//* src/constants/appErrorCode.js

/**
 * Centralized application error codes.
 *
 * @readonly
 * @enum {string}
 */
const appErrorCode = Object.freeze({
	// Authentication
	UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	USER_NOT_VERIFIED: "USER_NOT_VERIFIED",
	PROVIDER_MISMATCH: "PROVIDER_MISMATCH",
	GOOGLE_EMAIL_NOT_VERIFIED: "GOOGLE_EMAIL_NOT_VERIFIED",
	GITHUB_EMAIL_NOT_VERIFIED: "GITHUB_EMAIL_NOT_VERIFIED",
	ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",

	// Authorization
	INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
	CANNOT_ACT_ON_SELF: "CANNOT_ACT_ON_SELF",
	CANNOT_ACT_ON_PEER: "CANNOT_ACT_ON_PEER",
	LAST_SUPERADMIN: "LAST_SUPERADMIN",

	// User
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	ACCESS_DENIED: "ACCESS_DENIED",

	// File
	FILE_NOT_FOUND: "FILE_NOT_FOUND",
	FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
	FILE_RENAME_FAILED: "FILE_RENAME_FAILED",
	FILE_DELETE_FAILED: "FILE_DELETE_FAILED",
	FILE_TOO_LARGE: "FILE_TOO_LARGE",

	// Directory
	DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
	DIRECTORY_RENAME_FAILED: "DIRECTORY_RENAME_FAILED",
	DIRECTORY_DELETE_FAILED: "DIRECTORY_DELETE_FAILED",

	// Profile Picture
	INVALID_IMAGE_TYPE: "INVALID_IMAGE_TYPE",
	IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
	PROFILE_PICTURE_NOT_FOUND: "PROFILE_PICTURE_NOT_FOUND",

	// Validation
	INVALID_ID: "INVALID_ID",
	INVALID_ID_TOKEN: "INVALID_ID_TOKEN",
	INVALID_GITHUB_CODE: "INVALID_GITHUB_CODE",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	DUPLICATE_FIELD: "DUPLICATE_FIELD",

	// OTP
	INVALID_OTP: "INVALID_OTP",
	OTP_EXPIRED: "OTP_EXPIRED",
	OTP_COOLDOWN: "OTP_COOLDOWN",
	EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

	// General
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
	RATE_LIMITED: "RATE_LIMITED",

	// Drive Import
	INVALID_DRIVE_TOKEN: "INVALID_DRIVE_TOKEN",
	DRIVE_ITEM_NOT_FOUND: "DRIVE_ITEM_NOT_FOUND",
	DRIVE_IMPORT_FAILED: "DRIVE_IMPORT_FAILED",
	UNSUPPORTED_DRIVE_TYPE: "UNSUPPORTED_DRIVE_TYPE",
	DRIVE_EXPORT_TOO_LARGE: "DRIVE_EXPORT_TOO_LARGE",
	DRIVE_IMPORT_LIMIT_EXCEEDED: "DRIVE_IMPORT_LIMIT_EXCEEDED",
});

export default appErrorCode;
