//* src/constants/appErrorCode.js

/**
 * Centralized application error codes.
 *
 * @readonly
 * @enum {string}
 */
const appErrorCode = Object.freeze({
	// Authentication
	UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	USER_NOT_VERIFIED: "USER_NOT_VERIFIED",

	// User
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	ACCESS_DENIED: "ACCESS_DENIED",

	// File
	FILE_NOT_FOUND: "FILE_NOT_FOUND",
	FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
	FILE_RENAME_FAILED: "FILE_RENAME_FAILED",
	FILE_DELETE_FAILED: "FILE_DELETE_FAILED",

	// Directory
	DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
	DIRECTORY_RENAME_FAILED: "DIRECTORY_RENAME_FAILED",
	DIRECTORY_DELETE_FAILED: "DIRECTORY_DELETE_FAILED",

	// Validation
	INVALID_ID: "INVALID_ID",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	DUPLICATE_FIELD: "DUPLICATE_FIELD",

	// OTP
	INVALID_OTP: "INVALID_OTP",
	OTP_EXPIRED: "OTP_EXPIRED",
	OTP_COOLDOWN: "OTP_COOLDOWN",
	EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

	// General
	ALL_FIELDS_REQUIRED: "ALL_FIELDS_REQUIRED",
	EMAIL_REQUIRED: "EMAIL_REQUIRED",
	ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
});

export default appErrorCode;
